In [409]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [410]:
dataset = pd.read_csv('indian_liver_patient.csv')

In [660]:
X = dataset.iloc[: , [0,1,3,4,5,6,7,9]].values
y = dataset.iloc[: , -1].values

from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values = np.nan, strategy = 'most_frequent')
imputer = imputer.fit(X)
X = imputer.transform(X)

dataset.corr(method = 'pearson')

Age  Total_Bilirubin  Direct_Bilirubin  \
Age                         1.000000         0.011763          0.007529   
Total_Bilirubin             0.011763         1.000000          0.874618   
Direct_Bilirubin            0.007529         0.874618          1.000000   
Alkaline_Phosphotase        0.080425         0.206669          0.234939   
Alamine_Aminotransferase   -0.086883         0.214065          0.233894   
Aspartate_Aminotransferase -0.019910         0.237831          0.257544   
Total_Protiens             -0.187461        -0.008099         -0.000139   
Albumin                    -0.265924        -0.222250         -0.228531   
Albumin_and_Globulin_Ratio -0.216408        -0.206267         -0.200125   
Dataset                    -0.137351        -0.220208         -0.246046   

                            Alkaline_Phosphotase  Alamine_Aminotransferase  \
Age                                     0.080425                 -0.086883   
Total_Bilirubin                         0.206669                  0.214065   
Direct_Bilirubin                        0.234939                  0.233894   
Alkaline_Phosphotase                    1.000000                  0.125680   
Alamine_Aminotransferase                0.125680                  1.000000   
Aspartate_Aminotransferase              0.167196                  0.791966   
Total_Protiens                         -0.028514                 -0.042518   
Albumin                                -0.165453                 -0.029742   
Albumin_and_Globulin_Ratio             -0.234166                 -0.002375   
Dataset                                -0.184866                 -0.163416   

                            Aspartate_Aminotransferase  Total_Protiens  \
Age                                          -0.019910       -0.187461   
Total_Bilirubin                               0.237831       -0.008099   
Direct_Bilirubin                              0.257544       -0.000139   
Alkaline_Phosphotase                          0.167196       -0.028514   
Alamine_Aminotransferase                      0.791966       -0.042518   
Aspartate_Aminotransferase                    1.000000       -0.025645   
Total_Protiens                               -0.025645        1.000000   
Albumin                                      -0.085290        0.784053   
Albumin_and_Globulin_Ratio                   -0.070040        0.234887   
Dataset                                      -0.151934        0.035008   

                             Albumin  Albumin_and_Globulin_Ratio   Dataset  
Age                        -0.265924                   -0.216408 -0.137351  
Total_Bilirubin            -0.222250                   -0.206267 -0.220208  
Direct_Bilirubin           -0.228531                   -0.200125 -0.246046  
Alkaline_Phosphotase       -0.165453                   -0.234166 -0.184866  
Alamine_Aminotransferase   -0.029742                   -0.002375 -0.163416  
Aspartate_Aminotransferase -0.085290                   -0.070040 -0.151934  
Total_Protiens              0.784053                    0.234887  0.035008  
Albumin                     1.000000                    0.689632  0.161388  
Albumin_and_Globulin_Ratio  0.689632                    1.000000  0.163131  
Dataset                     0.161388                    0.163131  1.000000

In [661]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [662]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state=0)

In [663]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)
y_train = y_train-1
y_test = y_test-1

In [664]:
from sklearn.svm import SVC
classifier = SVC(kernel = 'linear', random_state=0)
classifier.fit(X_train, y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
    kernel='linear', max_iter=-1, probability=False, random_state=0,
    shrinking=True, tol=0.001, verbose=False)

In [665]:
y_pred1 = classifier.predict(X_test)

In [666]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred1)
print(cm)
accuracy_score(y_test,y_pred1)

[[78  0]
 [39  0]]


0.6666666666666666

In [667]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors = 15, metric = 'minkowski', p = 2)
classifier.fit(X_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=15, p=2,
                     weights='uniform')

In [668]:
y_pred2 = classifier.predict(X_test)

In [669]:
cm = confusion_matrix(y_test, y_pred2)
print(cm)
accuracy_score(y_test,y_pred2)

[[72  6]
 [33  6]]


0.6666666666666666

In [670]:
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(X_train, y_train)

GaussianNB(priors=None, var_smoothing=1e-09)

In [671]:
y_pred3 = classifier.predict(X_test)

In [672]:
cm = confusion_matrix(y_test, y_pred3)
print(cm)
accuracy_score(y_test,y_pred3)

[[32 46]
 [ 1 38]]


0.5982905982905983

In [673]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators = 23
                                    , criterion = 'entropy',random_state=0)
classifier.fit(X_train, y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='entropy',
                       max_depth=None, max_features='auto', max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=23,
                       n_jobs=None, oob_score=False, random_state=0, verbose=0,
                       warm_start=False)

In [674]:
y_pred4 = classifier.predict(X_test)

In [675]:
from sklearn.metrics import accuracy_score, confusion_matrix
cm = confusion_matrix(y_test, y_pred4)
print(cm)
accuracy_score(y_test, y_pred4)

[[72  6]
 [30  9]]


0.6923076923076923

In [676]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression()
classifier.fit(X_train, y_train)

C:\Users\nishith\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [677]:
y_pred5 = classifier.predict(X_test)

In [678]:
from sklearn.metrics import accuracy_score, confusion_matrix
cm = confusion_matrix(y_test, y_pred5)
print(cm)
accuracy_score(y_test, y_pred5)

[[73  5]
 [34  5]]


0.6666666666666666